### ISSUE TITLE
Make it more user friendly

### ISSUE THREAD

**Issue by wtremmel** [DE-CIX/udp-dtls-wrapper#2]
Please add at least a -h --help option

also, having the target not asked interactively but via option would be great (both - IP target AND UDP target port)
and an (optional) option to select not only the source interface (via IP) but also the source port.

**Comment by de-cix-role** [comment]
-h / --help added in f8a111d532095522f2be3f9461bb3ee4a5cefada
Also added --listen <ip> as a mandatory flag.
Usage now is:
  -listen string
    	Address to listen to.	Format: <ip addr>[:2055].
  -output string
    	Address to output to.	Format: [127.0.0.1][:2055] (default "127.0.0.1")
